import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

test('npm distribution excludes generated bytecode and dependencies while retaining native entrypoints', t => {
  const temporary = mkdtempSync(join(tmpdir(), 'stip-npm-distribution-'));
  t.after(() => rmSync(temporary, { recursive: true, force: true }));
  const distribution = join(temporary, 'distribution');
  const write = (path, content = 'fixture\n') => {
    mkdirSync(dirname(join(distribution, path)), { recursive: true });
    writeFileSync(join(distribution, path), content);
  };
  // Exercise the actual published allowlist, not a separate approximation of it.
  write('package.json', readFileSync(join(ROOT, 'package.json')));
  for (const directory of ['scripts', 'skills', 'packages/opencode/assets']) {
    write(`${directory}/.npmignore`, readFileSync(join(ROOT, directory, '.npmignore')));
  }
  const required = [
    'bin/install.mjs', 'bin/plugin-install.mjs', 'scripts/workflow.py',
    'skills/stip-bootstrap/SKILL.md', 'skills/stip-bootstrap/scripts/workflow.py',
    'packages/opencode/package.json', 'packages/opencode/package-lock.json',
    'packages/opencode/index.ts', 'packages/opencode/tui.tsx', 'packages/opencode/rpc.ts',
    'packages/opencode/src/index.ts', 'packages/opencode/src/tui.tsx',
    'packages/opencode/assets/workflow.py',
  ];
  for (const path of required) write(path, path.endsWith('package.json') ? '{"name":"@stipulate/opencode","version":"0.1.0"}' : 'fixture\n');
  const excluded = [
    'scripts/__pycache__/workflow.cpython-314.pyc',
    'scripts/workflow.pyc',
    'skills/stip-bootstrap/scripts/__pycache__/workflow.cpython-314.pyc',
    'skills/stip-bootstrap/scripts/workflow.pyo',
    'packages/opencode/assets/__pycache__/workflow.cpython-314.pyc',
    'packages/opencode/assets/workflow.pyd',
    'packages/opencode/node_modules/unwanted/index.js',
    'skills/stip-bootstrap/node_modules/unwanted/index.js',
  ];
  for (const path of excluded) write(path);
  const result = spawnSync(process.platform === 'win32' ? 'npm.cmd' : 'npm', ['pack', '--dry-run', '--json', '--ignore-scripts', '--offline', '--cache', join(temporary, 'npm-cache')], { cwd: distribution, encoding: 'utf8', shell: false });
  assert.equal(result.status, 0, result.stderr);
  const files = new Set(JSON.parse(result.stdout)[0].files.map(file => file.path));
  for (const path of required) assert.ok(files.has(path), `Required distribution file missing: ${path}`);
  for (const path of excluded) assert.ok(!files.has(path), `Generated artifact leaked into distribution: ${path}`);
  assert.ok([...files].every(path => !path.includes('/node_modules/') && !path.includes('/__pycache__/')));
});
